// AUTO-GENERATED by tools/gen_functions.py -- DO NOT HAND-EDIT.
// Source of truth: schema/functions.json.
#pragma once
#include <cstdint>
#include <sasdk/core/invoke.hpp>
#include <sasdk/game/sa10us/sa10us_db.inl>

namespace sasdk::sa10us::fn {

using sasdk::rt::CallConv;

// [SASDK UNVERIFIED -- catalogued, not yet confirmed by a disassembly pass]
// FindPlayerPed  @ 0x0056E210  (cdecl)  -- player ped; arg is player index (-1 = default).
inline const sasdk::rt::Function<CallConv::Cdecl, CPed*, std::int32_t> FindPlayerPed{0x0056E210u};

// [SASDK UNVERIFIED -- catalogued, not yet confirmed by a disassembly pass]
// FindPlayerVehicle  @ 0x0056E0D0  (cdecl)  -- player's current vehicle or null; (playerId=-1, includeRemote=false).
inline const sasdk::rt::Function<CallConv::Cdecl, CVehicle*, std::int32_t, bool> FindPlayerVehicle{0x0056E0D0u};

// [SASDK UNVERIFIED -- catalogued, not yet confirmed by a disassembly pass]
// FindPlayerHeading  @ 0x0056E450  (cdecl)  -- player heading in radians.
inline const sasdk::rt::Function<CallConv::Cdecl, float, std::int32_t> FindPlayerHeading{0x0056E450u};

// [SASDK VERIFIED -- address disassembly-confirmed]
// CStreaming_RemoveAllUnusedModels  @ 0x0040CF80  (cdecl)  -- CStreaming::RemoveAllUnusedModels; free the churn.
inline const sasdk::rt::Function<CallConv::Cdecl, void> CStreaming_RemoveAllUnusedModels{0x0040CF80u};

// [SASDK VERIFIED -- address disassembly-confirmed]
// CStreaming_RenderEntity  @ 0x004096D0  (cdecl)  -- CStreaming::RenderEntity(CEntity*).
inline const sasdk::rt::Function<CallConv::Cdecl, void, void*> CStreaming_RenderEntity{0x004096D0u};

// [SASDK VERIFIED -- address disassembly-confirmed]
// CEntity_SetModelIndexNoCreate  @ 0x00533700  (thiscall)  -- sets m_nModelIndex without creating the RwObject.
inline const sasdk::rt::MemberFunction<void, void, std::uint32_t> CEntity_SetModelIndexNoCreate{0x00533700u};

// [SASDK UNVERIFIED -- catalogued, not yet confirmed by a disassembly pass]
// CEntity_CreateRwObject  @ 0x00533D30  (thiscall)  -- builds the entity's RwObject; writes m_pRwObject@0x18.
inline const sasdk::rt::MemberFunction<void, void> CEntity_CreateRwObject{0x00533D30u};

// [SASDK UNVERIFIED -- catalogued, not yet confirmed by a disassembly pass]
// CVehicle_Fix  @ 0x006D6390  (thiscall)  -- repair to full; resets m_fHealth to 1000.0f.
inline const sasdk::rt::MemberFunction<void, void> CVehicle_Fix{0x006D6390u};

// [SASDK REASONED -- derived, not cold-proven]
// CWanted_UpdateWantedLevel  @ 0x00561C90  (thiscall)  -- recompute stars from chaos.
inline const sasdk::rt::MemberFunction<void, void> CWanted_UpdateWantedLevel{0x00561C90u};

} // namespace sasdk::sa10us::fn
